# -*- coding: utf-8 -*-
"""projeto_DIO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mTFLI1u-IWcr1kysfHdwv31B9_fOi2tI
"""

!pip install requests python-docx

from os import path
import requests
from docx import Document
import os

sub_key = "API_KEY"
endpoint = 'ENDPOINT_URL'
location = "eastus2"
target_language = 'pt-br'

def translate_text(text, target_language):
    constructed_url = endpoint + '/translate'
    headers = {
        'Ocp-Apim-Subscription-Key': sub_key,
        'Ocp-Apim-Subscription-Region': location,
        'Content-type': 'application/json',
        'X-ClientTraceId': str(os.urandom(16))
    }
    body = [{'text': text}]
    params = {
        'api-version': '3.0',
        'from': 'en',
        'to': target_language
    }
    response = requests.post(constructed_url, params=params, headers=headers, json=body)
    if response.status_code != 200:
        raise Exception(f"Erro na API de tradução: {response.status_code}, {response.text}")
    response_json = response.json()
    return response_json[0]["translations"][0]["text"]

def translate_document(path):
    document = Document(path)
    full_text = []
    for paragraph in document.paragraphs:
        if paragraph.text.strip():
            translated_text = translate_text(paragraph.text, target_language)
            full_text.append(translated_text)
    translated_doc = Document()
    for line in full_text:
        translated_doc.add_paragraph(line)
    path_translated = path.replace(".docx", f"_{target_language}.docx")
    translated_doc.save(path_translated)
    return path_translated

input_file = "/content/Bones.docx"
translate_document(input_file)

